### ISSUE TITLE
[warning] Unexpected input(s)

### ISSUE THREAD

**Issue by kaankoken** [streetsidesoftware/cspell-action#1615]
After migrating from `v5` to `v6` of the action. I received the `warning` on GitHub action.

```bash
Unexpected input(s) 'github_token', valid inputs are ['files', 'incremental_files_only', 'config', 'root', 'inline', 'strict', 'verbose', 'check_dot_files', 'use_cspell_files']
```

**ci.yaml**
```yaml
name: CI

on:
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  start:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4
      
  spell-check:
    runs-on: ubuntu-latest
    needs: [ start ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
     
      - name: Spell Check with Cspell
        uses: streetsidesoftware/cspell-action@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config: './config/cspell.config.yaml'
          inline: error
          verbose: true
```

**cspell.config.yaml**
```yaml
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: ci
    path: './dictionary/ci.txt'
    addWords: true
ignorePaths:
  - "**/*/build"
  - "**/*/dist"
  - "**/*/target"
  - "**/.vscode/**/"
  - "**/*.json"
  - "**/cspell.config.yaml"
  - "**/config/"
  - "**/node_modules/"
  - .github/workflows/
  - docs/
  - "**/*/.pre-commit-config.yaml"
  - '**/*/build/**/'
  - "**/*/pnpm*"
  - "**/*/*.toml"
  - "**/*/.gitignore"
dictionaries: ["ci"]
ignoreWords:
  - autofix
  - linebreak
  - elopment
  - abeta
  - Kaan
  - Köken
  - kaankoken
import: []
```
