### ISSUE TITLE
No documentation on cspell.json

### ISSUE THREAD

**Issue by GeorgeXCV** [streetsidesoftware/cspell-action#1695]
I see `cspell.json` referenced and I assume it is the config file but no documentation on it in the ReadMe. Where should the file be? How can I exclude words and file directories?

**Comment by Jason3S** [comment]
This action uses [`cspell`](https://github.com/streetsidesoftware/cspell/tree/main/packages/cspell#readme) to do the spell checking.

- [Getting Started with CSpell | CSpell](https://cspell.org/docs/getting-started/) should be a good place to start.

I suggest creating: `.config/cspell.config.yaml`. The action will find it.

`.config/cspell.config.yaml`

```yaml
ignorePaths: # glob patterns to ignore
  - cspell*.{yaml,json}
  - node_modules
words: # words to add to dictionary
  - MyCompanyName
ignoreWords: # words to ignore, but not suggest
  - todos
flagWords: # words to flag as forbidden with optional suggestions indicated by `->`.
  - blacklist->denylist
  - whitelist->allowlist
  - café->cafe
  - bluelist->greenList
  - Bluelist->GreenList
```
