### ISSUE TITLE
Support All Official cspell Dictionaries

### ISSUE THREAD

**Issue by Kurt-von-Laven** [streetsidesoftware/cspell-action#181]
This action is especially convenient for spell checking projects where installing a first Node.js package solely for the purpose of spell checking is difficult to justify. It would be ideal if it supported [all of the official cspell dictionaries](https://github.com/streetsidesoftware/cspell-dicts). I think the workaround is either to create a package.json with one dependency (the dictionary) in our C# project that uses NuGet package manager or to check a copy of the raw dictionary text file itself into our repository.

**Comment by Jason3S** [comment]
Trying to support all dictionaries would make this action huge. Maybe a way of downloading them on the fly might work.

**Comment by Kurt-von-Laven** [comment]
Yeah, I have come to agree with you since filing this issue as I have realized that pulling actions down is itself one of the most expensive operations we do. I think even just showing an example of a `yarn add @cspell/dict-foo@va.b.c` or `npm install @cspell/dict-foo@va.b.c` as the preceding step in the README would actually be all that is needed?

**Comment by guidemetothemoon** [comment]
Hi @Jason3S , I'm facing an issue with making additional dictionaries to work with GH action and in search of documentation I came across this issue. Can you please point out what I may be doing wrong here? Thanks in advance!

My workflow looks like this:
```
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - run: npm install -g @cspell/dict-es-es
    
    - name: Validate spelling
      uses: streetsidesoftware/cspell-action@v5.4.0
      with:
        config: 'cspell.json'
        files: '**/*.md'
        inline: 'error'
        strict: true        
        incremental_files_only: true
```

cspell.json looks like this:
```
{
    "version": "0.2",
    "import": ["@cspell/dict-es-es/cspell-ext.json"],
    "language": "en,es",
----------  OMITTED ---------
}
```
I'm getting the following error when executing with this configuration:
```
Run streetsidesoftware/cspell-action@v5.4.0
  with:
    config: cspell.json
    files: **/*.md
    inline: error
    strict: true
    incremental_files_only: true
    github_token: ***
    verbose: false
    check_dot_files: explicit
cspell-action
Pull Request
Fetch file names in commits: 6.242s
Error: Configuration
        name: Error
        msg: Failed to resolve file: "@cspell/dict-es-es/cspell-ext.json"
        stack:
Error: Failed to resolve file: "@cspell/dict-es-es/cspell-ext.json"
    at ConfigLoaderInternal.resolveFilename (/home/runner/work/_actions/streetsidesoftware/cspell-action/v5.4.0/action/lib/main_root.js:67131:33)
    at async Promise.all (index 0)
    at async ConfigLoaderInternal._mergeConfigFileWithImports (/home/runner/work/_actions/streetsidesoftware/cspell-action/v5.4.0/action/lib/main_root.js:67044:23)
    at async onReadyFixUp (/home/runner/work/_actions/streetsidesoftware/cspell-action/v5.4.0/action/lib/main_root.js:67002:24)
    at async readConfig (/home/runner/work/_actions/streetsidesoftware/cspell-action/v5.4.0/action/lib/main_root.js:75548:21)
    at async run2 (/home/runner/work/_actions/streetsidesoftware/cspell-action/v5.4.0/action/lib/main_root.js:76329:24)
    at async runLint (/home/runner/work/_actions/streetsidesoftware/cspell-action/v5.4.0/action/lib/main_root.js:76100:22)
    at async lint2 (/home/runner/work/_actions/streetsidesoftware/cspell-action/v5.4.0/action/lib/main_root.js:76701:3)
    at async checkSpelling (/home/runner/work/_actions/streetsidesoftware/cspell-action/v5.4.0/action/lib/main_root.js:76739:3)
    at async action (/home/runner/work/_actions/streetsidesoftware/cspell-action/v5.4.0/action/lib/main_root.js:76807:18)
        
Files checked: 0, Issues found: 0 in 0 files.
Done.
```

**Comment by gaby** [comment]
I have several dictionaries installed, but i can't tell if cspell is using them or not. It doesn't print a list of dictionaries or anything even in `verbose`. The `verbose` flag barely makes a difference.

workflow

```yaml
name: Spell check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  cspell:
    name: cspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20.x"

      - name: Install cspell dictionaries
        run: |
          npm install --no-save \
            @cspell/dict-en_us \
            @cspell/dict-en-gb \
            @cspell/dict-software-terms \
            @cspell/dict-golang \
            @cspell/dict-fullstack \
            @cspell/dict-docker \
            @cspell/dict-k8s \
            @cspell/dict-node \
            @cspell/dict-npm \
            @cspell/dict-typescript \
            @cspell/dict-html \
            @cspell/dict-css \
            @cspell/dict-shell \
            @cspell/dict-python \
            @cspell/dict-redis \
            @cspell/dict-sql \
            @cspell/dict-filetypes \
            @cspell/dict-companies \
            @cspell/dict-markdown \
            @cspell/dict-en-common-misspellings \
            @cspell/dict-people-names \
            @cspell/dict-data-science

      - name: Run cspell
        uses: streetsidesoftware/cspell-action@v7
        with:
          incremental_files_only: false
          check_dot_files: explicit
```

cspell config:

```json
{
  "version": "0.2",
  "language": "en, en-gb, en-us",
  "useGitignore": true,
  "caseSesnsitive": false,
  "unknownWords": "report-common-typos",
  "import": [
    "@cspell/dict-en_us/cspell-ext.json",
    "@cspell/dict-en-gb/cspell-ext.json",
    "@cspell/dict-software-terms/cspell-ext.json",
    "@cspell/dict-golang/cspell-ext.json",
    "@cspell/dict-fullstack/cspell-ext.json",
    "@cspell/dict-docker/cspell-ext.json",
    "@cspell/dict-k8s/cspell-ext.json",
    "@cspell/dict-node/cspell-ext.json",
    "@cspell/dict-npm/cspell-ext.json",
    "@cspell/dict-typescript/cspell-ext.json",
    "@cspell/dict-html/cspell-ext.json",
    "@cspell/dict-css/cspell-ext.json",
    "@cspell/dict-shell/cspell-ext.json",
    "@cspell/dict-python/cspell-ext.json",
    "@cspell/dict-redis/cspell-ext.json",
    "@cspell/dict-sql/cspell-ext.json",
    "@cspell/dict-filetypes/cspell-ext.json",
    "@cspell/dict-companies/cspell-ext.json",
    "@cspell/dict-markdown/cspell-ext.json",
    "@cspell/dict-en-common-misspellings/cspell-ext.json",
    "@cspell/dict-people-names/cspell-ext.json"
  ],
  "dictionaries": [
    "en_us",
    "en-gb",
    "softwareTerms",
    "web-services",
    "networking-terms",
    "software-term-suggestions",
    "software-services",
    "software-terms",
    "software-tools",
    "coding-compound-terms",
    "golang",
    "fullstack",
    "docker",
    "k8s",
    "node",
    "npm",
    "typescript",
    "html",
    "css",
    "shell",
    "python",
    "redis",
    "sql",
    "filetypes",
    "companies",
    "markdown",
    "en-common-misspellings",
    "people-names",
    "data-science",
    "data-science-models",
    "data-science-tools"
  ],
  "ignorePaths": [
    ".git",
    "node_modules",
    "vendor",
    "internal",
    ".github",
    "**/*.svg",
    "**/*.png",
    "**/*.jpg",
    "**/*.jpeg",
    "**/*.gif",
    "**/*.ico",
    "**/*.lock",
    "**/*_gen.go",
    "**/*_msgp.go",
    "**/*_msgp_test.go",
    "**/*_test.go",
    "go.mod",
    "go.sum",
    ".golangci.yml",
    ".markdownlint.yml",
    "AGENTS.md"
  ]
}
```

We get a massive amount of `unknown words`, with no way of disabling them. We don't care about unknown words, only misspells.
