### ISSUE TITLE
`incremental_files_only` appears to be ignored

### ISSUE THREAD

**Issue by tpeterson-metropolis** [streetsidesoftware/cspell-action#2325]
I'm seeing a pair of issues:

1. Typos from a PR are not caught until the code is merged
2. Said typos are then picked up in unrelated changes despite those files not being touched in those changes

Details from action run:
```
Run streetsidesoftware/cspell-action@eb29b6a67d122d2e6af385ff16bdb200d93b2e54
  with:
    check_dot_files: true
    config: ./.github/spelling/cspell.json
    suggestions: true
    incremental_files_only: true
    inline: warning
    treat_flagged_words_as_errors: false
    strict: true
    verbose: false
    use_cspell_files: false
```
