### ISSUE TITLE
Spelling Isn't Checked When Incremental Mode Disabled

### ISSUE THREAD

**Issue by Kurt-von-Laven** [streetsidesoftware/cspell-action#318]
When passing `incremental_files_only: false` in a workflow triggered by a pull request event, the cspell action outputs the following and executes in 0 seconds:
```
Run streetsidesoftware/cspell-action@v1.2.4
  with:
    incremental_files_only: false
    github_token: ***
    inline: warning
    strict: true
cspell-action
Pull Request
Done.
```

**Comment by Jason3S** [comment]
Thank you. I would need to take a look at what is going on.

Does `files: "**"` work for you?

```
with:
  files: "**"
```

**Comment by Kurt-von-Laven** [comment]
Good call! Yes, it does.

**Comment by owenbendavies** [comment]
I am having the same issue. Adding `files: "**"` does work however then it doesn't check hidden files:

```
      - uses: streetsidesoftware/cspell-action@v1
```

works for just checking files that have changed

```
      - uses: streetsidesoftware/cspell-action@v1
        with:
          incremental_files_only: false
```

doesn't check any files

```
      - uses: streetsidesoftware/cspell-action@v1
        with:
          files: '**'
          incremental_files_only: false
```

checks all non hidden files, can't think of a single glob to do both hidden and non hidden files, and doesn't support array of globs like cspel.json files setting.

Thank you.

**Comment by Jason3S** [comment]
@owenbendavies,

If you add `enableGlobDot` to your `cspell.json` file.

```
    "enableGlobDot": true
```

It should should check hidden files.

**Comment by owenbendavies** [comment]
Ahh thank you, missed that option in the docs. So for now as reference for others I have this in my Github action:

```yaml
      - uses: streetsidesoftware/cspell-action@v1
         with:
           files: '**'
           incremental_files_only: false
```

And this in my `.cypress.json`

```json
{
  "version": "0.2",
  "enableGlobDot": true,
  "files": ["**"],
  "ignorePaths": [".git"],
  "useGitignore": true,
```

(files in the cypress.json is so I can run locally as well)

Thank you for your help, and for this really good github action as is nicer than running as a command in the github action.

Owen
