### ISSUE TITLE
Hidden folders are not ignored when the the working directory is not the root

### ISSUE THREAD

**Issue by ValentinVignal** [streetsidesoftware/cspell-action#750]
I have a project like this

```
.github/
  |- workflows/
  |    |- cspell_workflow.yaml
packages/
  |- .hidden/
  |    |- text.txt
  |- cspell.json
  |- text.txt
```

With `packages/cspell.json`:

```json
{
  "ignorePaths": [
    ".hidden/text.txt"
  ],
  "words": [
    "ignoredword"
  ]
}
```

And `.github/workflows/cspell_workflow.yaml`:

```yaml
name: cSpell
on: [pull_request]
jobs:
  cspell:
    runs-on: ubuntu-latest
    name: cspell
    defaults:
      run:
        working-directory: packages # The entire project and configuration files are in the folder "packages".
    steps:
      - uses: actions/checkout@v3
      - name: cspell
        uses: streetsidesoftware/cspell-action@v2
```

When the job `cspell` runs, it doesn't ignore the `.hidden` folder as specified in the `packages/cspell.json`.

You can check the run https://github.com/ValentinVignal/examples/runs/6671863347?check_suite_focus=true :
- `badword` in `packages/text.txt` is linted (as it should be)
- `ignoredword` in `packages/text.txt` is not linted (as it should be)
- `badwordinignoredfile` in `packages/.hidden/text.txt` is linted  (and it shouldn't )

You can also check the PR https://github.com/ValentinVignal/examples/pull/1 where I made several tries and its branch: https://github.com/ValentinVignal/examples/tree/cspell/nested-configuration
