### ISSUE TITLE
Can't use cspell.json from a URL?

### ISSUE THREAD

**Issue by Nightblade** [streetsidesoftware/cspell-action#869]

**Comment by nicorikken** [comment]
This would be great. I'm now looking to deploy a default cspell action in my organization. Now I'd have to wrap the cspell-action in a action that takes care of writing/copying the organization-default `cspell.json` and installing dictionaries. Having that be part of cspell or cspell-action would be great.

**Comment by quicksketch** [comment]
If you dictionary file and `cspell.json` are both in the same repository, you can just check out both this action and the dictionary/configuration in a single GitHub workflow like this:

```
  spellcheck:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout code
    - uses: actions/checkout@v4
      name: Checkout cspell config
      with:
        repository: backdrop-ops/cspell
        path: .cspell
    - uses: streetsidesoftware/cspell-action@v5
      name: Run CSpell
      with:
        incremental_files_only: true
        config: '.cspell/cspell.json'
```

Then you don't need to use remote URLs at all, because the files you need are checked out into the local directory before the action is run.

That's what we are about to do over in https://github.com/backdrop/backdrop-issues/issues/6280.
